### PR TITLE
Use pio version 0.11.0-incubating

### PR DESCRIPTION
**Pull request by jsyrjala**

### CODE REVIEW

**Comment by pferrel** [comment]
Actually 0.12.0 was just released

**Comment by jsyrjala** [comment]
Currently the build fails with this error:
```
[ERROR] [Engine$] [error] (*:update) sbt.ResolveException: unresolved dependency: org.apache.predictionio#apache-predictionio-core_2.10;0.11.0-SNAPSHOT: not found
```

**Comment by pferrel** [comment]
You just have to change the PIO version in the build.sbt. There is probably no need to change the spark versions or others.

**Comment by jsyrjala** [comment]
Yes, changing pio version will fix the problem. This merge request will fix the above problem by changing the PIO version to a version that the build can find.. 

I can make a pull request that changes the version to 0.12.0-incubating, if you prefer. That will work also.

**Comment by pferrel** [comment]
Why not use pio 0.12.0, the latest version?

**Pull request merged**
